CREATE TABLE userRegister (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(100) NOT NULL,
    dateRegister TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);